// LOCALHOST
###
GET http://localhost:8080/contacts HTTP/1.1
###
GET http://localhost:8080/contacts/644be97f120bd798503c7f0a
###
GET http://localhost:8080/contacts/644be9fc120bd798503c7f0b
###
GET http://localhost:8080/contacts/644bea15120bd798503c7f0c

PRODUCTION
###
